# 스프링 기본 설정
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/social
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  mvc:
    static-path-pattern: /**

# jwt
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

# 로깅 설정
logging:
  level:
    org.hibernate.sql: debug