spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/social
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true

logging:
  level:
    org.hibernate.sql: debug